#!/bin/bash
#
# Get WAN IP from Router status page : DLINK DIR600
# CAUTION: Requires to disable graphical authentication
#          (See router maintenance page)
#

## Router address (default)
router=192.168.1.1

## Login/Admin parameters in clear (here here) or from a credentials
## file with appropriate and restricted permissions.
username=
password=

## Config file 
configfile=$0.conf
if [ -f $configfile ]; then
    . $configfile
fi

## Router parameters
login=http://$router/login.php
logout=http://$router/logout.php
status=http://$router/st_device.php

## Quit silently if not configured.
[ -z "$router" ] || [ -z "$username" ] || [ -z "$password" ] && \
    exit 20;

## Acquire the status page
postdata="ACTION_POST=LOGIN&FILECODE=&VERIFICATION_CODE=&LOGIN_USER=$username&LOGIN_PASSWD=$password&login=Log+In+&VER_CODE="

# - Login or returning without result
wget="wget -o /dev/null -O - -t 1 -T 5"
$wget --post-data=$postdata $login | grep -oq bsc_internet || exit 1;

# - Get status page limited to lines containing 'wanipaddr'
ipstr=$($wget $status | grep wanipaddr)

# - Logout
$wget $logout > /dev/null

## Extract relevant data in two steps
regexp0='wanipaddr\"\s*>[^<]*'
regexp='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
echo $ipstr|grep -Poe $regexp0|grep -Poe $regexp
