#!/bin/bash
#
url=http://www.all-nettools.com/toolbox/environmental-variables-test.php
regexp0='REMOTE_ADDR\s*:\s*</td>\s*<td>\s*[^<]*'
regexp='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
wget="wget -o /dev/null -O - -t 1 -T 5"
$wget $url|grep -Poe "$regexp0"|grep -Poe $regexp
