#!/bin/bash

url=http://www.showmyipaddress.com/
regexp0='<strong'
regexp='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
wget="wget -o /dev/null -O - -t 1 -T 5"
$wget $url|grep -Pe "$regexp0"|grep -Poe $regexp

