#!/bin/bash
#
url=http://www.whatismyip.com.au/
regexp0='Your IP address'
regexp='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
wget="wget -o /dev/null -O - -t 1 -T 5"
$wget $url|grep -e "$regexp0"|grep -Poe $regexp
