#!/bin/bash
#
# Available proxy dnsexit servers:
declare -a proxyservs=(ip.dnsexit.com ip2.dnsexit.com ip3.dnsexit.com);

# Pick one at (very pseudo) random
num=$(($(date +%s)%3))
url=http://${proxyservs[$num]}

regexp='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
wget="wget -o /dev/null -O - -t 1 -T 5"
$wget $url|grep -Poe $regexp
