#!/bin/bash
#
# Yet another Dynamic IP controller - Script to execute
# commands/actions upon WAN IP changes.
#
# Author:	Th. Walrant <yadynip.tgc@walrant.net>
# Date:		May 2014
#
# Detection:
# The tool accepts multiple ways to detect the WAN IP address by
# executing the different checkip scripts until one an IP is found
# (See the checkip.d folder for available methods/scripts). You can
# add your own method and/or disable some scripts by deleting the
# script file or by updating the script to return/exit without
# returning an IP address.
#
# Actions:
# Once the IP address is detected, the tool check all available
# actions (located in folder actions.d). It executes the script only
# if the IP address has changed. The IP address is cached per action
# upon succesful execution of the action. The tool is able to only
# repeat the action who failed at the previous attempt.
#
name=yadynip
installdir=$(dirname $0)
installdir=${installdir%%/bin}

sharedir=$installdir/share/$name
etcdir=$installdir/etc/$name
config=$installdir/etc/$name/$name.conf

for conf in $config ~/$name.conf $installdir/$name.conf; do
    if [ -f $conf ]; then
	. $conf
    fi
done

checkipdir=$etcdir/checkip.d
actionsdir=$etcdir/actions.d
ipcachedir=$sharedir/ipcaches

verbose() {
    [ "$quiet" != 'on' ] && return;
    echo $*
}

logdebug() {
    [ "$logging" != 'debug' ] && return;
    verbose $*
    echo $(date -R) DEBUG $* >> $logfile
}

logverbose() {
    verbose $*
    [ "$logging" != 'verbose' ] && [ "$logging" != 'debug' ] && return;
    echo $(date -R) $* >> $logfile
}

## Get my WAN IP address using available checkip scripts
wanip=
for f in $checkipdir/*; do
    # Skip backup file and folder
    [ -d $f ] && continue
    echo $f | grep -Pqe "~$" && continue

    # Get my WAN IP
    wanip=$($f)
    logdebug $f returns $wanip;

    # Stop here if an IP address is found
    test -n "$wanip" && break
done

## Stop here if no WAN IP Address is found
test -z "$wanip" && echo "$name: No WAN IP Address found" && exit;

logverbose "WAN IP Address= " $wanip

## Perform actions with detected IP address
touch $actionsdir/99ignore~
for f in $actionsdir/*; do
    # Skip backup file and folder
    [ -d $f ] && continue
    echo $f | grep -Pqe "~$" && continue

    # Get and check last known IP address for this action
    lastip=
    ipcache=$ipcachedir/$(basename $f)
    [ -f $ipcache ] && lastip=$(cat $ipcache)

    # Skip this action if no new IP address
    [ "$lastip" == "$wanip" ] && continue

    # Execute the action, abort upon error.
    logverbose Execute $f $wanip
    $f $wanip || continue

    # Update known IP address for this action
    echo $wanip > $ipcache
done
