#!/bin/bash
#
# Courtesy of doegox - see
# http://wiki.yobi.be/wiki/Bind#Update_from_client_automatically for
# details.
#
 
# Check argument - must be an IPv4 address
[ -z "$1" ] && exit 10;
regexp='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
[ "$(echo $1 | grep -Poe $regexp)" != "$1" ] && exit 11;

# Required variables:
host=
ns=

# Config file:
configfile=$0.conf
if [ -f $configfile ]; then
    . $configfile
fi
 
# Quit silently if not configured.
[ "$host" == "" ] || [ "$ns" == "" ] && \
    exit 20;

tooldir=$(basename $0)
tooldir=$(dirname $0)/${tooldir:2}
cd $tooldir
./dynaname -H $host -S $ns -A $1 || exit $?

echo "Dynaname update zone $host with $1"
 
# Successfull action exit with 0
exit 0;
