#!/bin/bash
#
# ZoneEdit dynamic dns client - script to update host(s) IP
# address(es).
#

# Check argument - must be an IPv4 address
[ -z "$1" ] && exit 1;
regexp='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
[ "$(echo $1 | grep -Poe $regexp)" != "$1" ] && exit 1;

## ZoneEdit parameters in clear (local here) or from the configuration
## file with appropriate and restricted permissions.
hosts=
username=
password=

## Config file 
configfile=$(basename $0)
configfile=$(dirname $0)/conf/${configfile:2}
if [ -n "$configfile" ] && [ -f $configfile ]; then
    . $configfile
fi

## Quit silently if not configured.
[ -z "$hosts" ] || [ -z "$username" ] || [ -z "$password" ] && exit 1;

## Update zone.
url="https://dynamic.zoneedit.com/auth/dynamic.html?host=$hosts&dnsto=$1"
wget -o /dev/null -O - --http-user=$username --http-passwd=$password $url | grep -q SUCCESS || exit 1;

# $2 holds the log filename
[ -z "$2" ] && exit 0;
echo $(date -R) "ZoneEdit update zone(s) $hosts with $1" >> $2

# Successfull action exit with 0
exit 0;
