#!/usr/bin/perl
#
use strict;
use File::Basename;
use Mail::Sendmail;

our $smtp;
our $from;
our $to;
our $subject = 'Dynamic IP changed';
our $message = 'New WAN IP address: %s';
our $hostname;

## Load config file if present or exit with success.
my $configfile = join ('/', dirname($0), 'conf', substr(basename($0), 2));
exit(0) unless -f $configfile;
require $configfile;

# Check mandatory config parameters
exit(1) unless $smtp;
exit(1) unless $from;
exit(1) unless $to;

# Check argument - must be an IPv4 address
exit(1) unless $ARGV[0];
exit(1) unless $ARGV[0] =~ /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/;

# Update 'To' and/or 'Message if required.
$to = join(';', @$to) if ref($to) =~ /ARRAY/;
$message = sprintf($message, $ARGV[0]);
$message .= sprintf(" (%s)", $hostname) if $hostname;

my %mail = ( To => $to,
	     From => $from,
	     Subject => $subject,
	     Message => $message,
	     Smtp => $smtp );

sendmail(%mail) or exit(1);
exit 0;
