#!/usr/bin/perl
#
use strict;
use File::Basename;
use Mail::Sendmail;
use POSIX qw(strftime);

our $smtp;
our $from;
our $to;
our $subject = 'Dynamic IP changed';
our $message = 'New WAN IP address: %s';
our $hostname;

## Load config file if present or exit with success.
my $configfile = join ('.', $0, 'conf');
require $configfile if -f $configfile;

# Check argument - must be an IPv4 address
exit(10) unless $ARGV[0];
exit(11) unless $ARGV[0] =~ /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/;

# Check mandatory config parameters
exit(20) unless $smtp;
exit(20) unless $from;
exit(20) unless $to;

# Update 'To' and/or 'Message if required.
$to = join(';', @$to) if ref($to) =~ /ARRAY/;
$message = sprintf($message, $ARGV[0]);
$message .= sprintf(" (%s)", $hostname) if $hostname;

my %mail = ( To => $to,
             From => $from,
             Subject => $subject,
             Message => $message,
             Smtp => $smtp );

sendmail(%mail) or exit(1);

printf("Report $ARGV[0] to $to\n");

# Successfull action exit with 0
exit(0);
